### Atividade
##### • A partir do dataset escolhido para trabalhar com os métodos supervisionados e a biblioteca scikitlearn do Python, realize as seguintes tarefas:
##### 1. Identifique o atributo alvo.
##### 2. Execute o algoritmo K-NN aplicando cross-validation (validação cruzada) para 10 KFolds.
##### 3. Execute o algoritmo K-NN aplicando Holdout, dividindo o dataset em 30% para teste.
##### 4. Altere o número de k para obter uma melhor acurácia na validação.
##### 5. Analise e compare os resultados obtidos, utilizando a matriz de confusão e computando a acurácia.

In [37]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

In [21]:
from sklearn.datasets import load_iris
data = load_iris()

In [28]:
X = data.data  # Atributos (características das flores)
y = data.target  # Atributo alvo (espécies das flores)

In [29]:
# Definir o modelo K-NN com k=5 (valor padrão)
knn = KNeighborsClassifier(n_neighbors=5)

In [30]:
# Aplicando validação cruzada com 10 folds
scores = cross_val_score(knn, X, y, cv=10)

In [31]:
# Dividindo o dataset (70% treino, 30% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [38]:
# Treinando o modelo K-NN
knn.fit(X_train, y_train)

# Realizando as previsões no conjunto de teste
y_pred = knn.predict(X_test)

# Acurácia e matriz de confusão
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [39]:
# Testando diferentes valores de k
k_values = range(1, 21)  # Testando k de 1 a 20
accuracies = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

# Encontrando o melhor k
best_k = k_values[np.argmax(accuracies)]
best_accuracy = max(accuracies)

print(f"Melhor valor de k: {best_k}")
print(f"Melhor acurácia: {best_accuracy}")

Melhor valor de k: 1
Melhor acurácia: 1.0


In [40]:
# Com o melhor k encontrado, treinando o modelo novamente
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train, y_train)
y_pred_best = knn_best.predict(X_test)

# Acurácia e matriz de confusão para o melhor k
accuracy_best = accuracy_score(y_test, y_pred_best)
conf_matrix_best = confusion_matrix(y_test, y_pred_best)

print(f"Acurácia com o melhor k ({best_k}): {accuracy_best}")
print(f"Matriz de Confusão com o melhor k:\n{conf_matrix_best}")

Acurácia com o melhor k (1): 1.0
Matriz de Confusão com o melhor k:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
